use fn_error_context::context;

#[context("context")]
async fn async_something() {
}

fn main() {
}
